#!/bin/bash

# Find all staged Python files
files=$(git diff --cached --name-only --diff-filter=d | grep '\.py$')

if [ -z "$files" ]; then
    echo "No Python files staged for commit."
    exit 0
fi

VENV_DIR="ci_venv"

if [ ! -d $VENV_DIR ]; then
    ./ci/ci_venv.sh
else
    echo ===== USING EXISTING CI_VENV =====
fi

source "$VENV_DIR/bin/activate"

echo "Running Black on staged files..."
black $files

if ! git diff --quiet; then
    echo "Python files were automatically formatted by black."
    echo "Please review the changes and commit again. (No commit made)"
    exit 1
fi

echo "Running Pylint on staged files..."
pylint_output=$(pylint $files)
overall_score=$(echo "$pylint_output" | grep 'Your code has been rated at' | awk '{print $7}' | sed 's,/10,,')
echo "$pylint_output"

if (( $(echo "$overall_score < 9" | bc -l) )); then
    echo "Pylint score is below 9." 
    echo "Please review Pylint messages and commit again. (No commit made)"
    exit 1
fi

echo "All Python files are properly formatted and linted. (Commit made locally)"
